name: Docker

on:
  push:
    branches:
      - main

  pull_request:

env:
  IMAGE_NAME: apg

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Test
        run: docker run -i --rm $IMAGE_NAME -m 24 -M SNCL

  # Push image to GitHub Container Registry
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/$GITHUB_ACTOR/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          
          docker push $IMAGE_ID:latest
          
